// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoDLBTCoV8Bzf27DeYi_ewK98YPM7_VfQ',
    appId: '1:944730886575:web:321dced1cdc71b793c1f5a',
    messagingSenderId: '944730886575',
    projectId: 'fir-practice-25877',
    authDomain: 'fir-practice-25877.firebaseapp.com',
    storageBucket: 'fir-practice-25877.appspot.com',
    measurementId: 'G-8ZCW4VJHX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFTyUxauM-R9gKkDbQVi5gdNx60JKZPs8',
    appId: '1:944730886575:android:797652950bebc3fd3c1f5a',
    messagingSenderId: '944730886575',
    projectId: 'fir-practice-25877',
    storageBucket: 'fir-practice-25877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhp818pQW8Y6DJa8Nyk3_WAqGyRq_ocoQ',
    appId: '1:944730886575:ios:314ed8cd617dfa773c1f5a',
    messagingSenderId: '944730886575',
    projectId: 'fir-practice-25877',
    storageBucket: 'fir-practice-25877.appspot.com',
    iosBundleId: 'com.example.hivepractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhp818pQW8Y6DJa8Nyk3_WAqGyRq_ocoQ',
    appId: '1:944730886575:ios:7f6be3b07621692a3c1f5a',
    messagingSenderId: '944730886575',
    projectId: 'fir-practice-25877',
    storageBucket: 'fir-practice-25877.appspot.com',
    iosBundleId: 'com.example.hivepractice.RunnerTests',
  );
}
